### ISSUE TITLE
[1.12.2] Log Error... sandstartool / sanstarpickaxe

### ISSUE THREAD

**Issue by PhoenixRiver** [pentantan/JapariCraftMod#4]
I just got this error when playing modded Minecraft with you mod installed:
Version: japaricraftmod-1.12-3.6.0
Forge: forge1.12.2-14.23.1.2555

```
[Server thread/ERROR] [FML]: Parsing error loading built-in advancement japaricraftmod:japaricraftmod/sandstartool
com.google.gson.JsonSyntaxException: Expected item to be an item, was unknown string 'japaricraftmod:sandstarpickaxe'
	at net.minecraft.util.JsonUtils.func_188172_b(SourceFile:124) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_188180_i(SourceFile:135) ~[rc.class:?]
	at net.minecraft.advancements.DisplayInfo.func_193221_a(DisplayInfo.java:133) ~[r.class:?]
	at net.minecraft.advancements.DisplayInfo.func_192294_a(DisplayInfo.java:111) ~[r.class:?]
	at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:202) ~[i$a.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
	at net.minecraftforge.common.ForgeHooks.lambda$loadAdvancements$0(ForgeHooks.java:1333) ~[ForgeHooks.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:821) [CraftingHelper.class:?]
	at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1315) [ForgeHooks.class:?]
	at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1289) [ForgeHooks.class:?]
	at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:69) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156) [oo.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:95) [chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:209) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

Hope this helps :)

**Comment by pentantan** [comment]
This issue fixed on 3.6.2
Thanks!
