### ISSUE TITLE
[1.12.2] Exception from loading map...

### ISSUE THREAD

**Issue by PhoenixRiver** [pentantan/JapariCraftMod#5]
This exception showed up in the logs during the map loading...
Version: japaricraftmod-1.12-3.6.0
Forge: forge1.12.2-14.23.1.2555

```
[17:42:06] [Server thread/WARN]: Failed Piece with id JH1
[17:42:06] [Server thread/INFO] [STDERR]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:97]: java.lang.InstantiationException: com.japaricraft.japaricraftmod.world.ComponentJapariHouse1
[17:42:06] [Server thread/INFO] [STDERR]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:97]: 	at java.lang.Class.newInstance(Class.java:427)
[17:42:06] [Server thread/INFO] [STDERR]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:97]: 	at net.minecraft.world.gen.structure.MapGenStructureIO.func_143032_b(SourceFile:93)
[17:42:06] [Server thread/INFO] [STDERR]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:97]: 	at net.minecraft.world.gen.structure.StructureStart.func_143020_a(StructureStart.java:105)
[17:42:06] [Server thread/INFO] [STDERR]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:97]: 	at net.minecraft.world.gen.structure.MapGenStructureIO.func_143035_a(SourceFile:80)
[17:42:06] [Server thread/INFO] [STDERR]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:97]: 	at net.minecraft.world.gen.structure.MapGenStructure.func_143027_a(MapGenStructure.java:201)
[17:42:06] [Server thread/INFO] [STDERR]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:97]: 	at net.minecraft.world.gen.structure.MapGenStructure.func_180701_a(MapGenStructure.java:30)
[17:42:06] [Server thread/INFO] [STDERR]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:97]: 	at net.minecraft.world.gen.MapGenBase.func_186125_a(SourceFile:34)
[17:42:06] [Server thread/INFO] [STDERR]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:97]: 	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_180514_a(ChunkGeneratorOverworld.java:604)
[17:42:06] [Server thread/INFO] [STDERR]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:97]: 	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:102)
[17:42:06] [Server thread/INFO] [STDERR]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:97]: 	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
[17:42:06] [Server thread/INFO] [STDERR]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:97]: 	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
[17:42:06] [Server thread/INFO] [STDERR]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:97]: 	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
[17:42:06] [Server thread/INFO] [STDERR]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:97]: 	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
[17:42:06] [Server thread/INFO] [STDERR]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:97]: 	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
[17:42:06] [Server thread/INFO] [STDERR]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:97]: 	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:186)
[17:42:06] [Server thread/INFO] [STDERR]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:97]: 	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:209)
[17:42:06] [Server thread/INFO] [STDERR]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:97]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
[17:42:06] [Server thread/INFO] [STDERR]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:97]: 	at java.lang.Thread.run(Thread.java:748)
[17:42:06] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NoSuchMethodException: com.japaricraft.japaricraftmod.world.ComponentJapariHouse1.<init>()
[17:42:06] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.lang.Class.getConstructor0(Class.java:3082)
[17:42:06] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.lang.Class.newInstance(Class.java:412)
[17:42:06] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	... 17 more
[17:42:06] [Server thread/WARN]: Skipping Piece with id JH1
```

Hope this helps :)

**Comment by pentantan** [comment]
I fixed in 3.9.8
thank you :D
